name: Use the Composite Action with Actions

on:
  workflow_dispatch:
  push:
    branches: ['test2']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read build-tool from YAML file
        id: read-yaml
        run: |
          build-tool=$(cat ./pipelineconfig.yml | yq e '.buildTool')
          export build-tool
          echo $build-tool
        shell: bash
        env:
          path: ${{ github.workspace }}

  other-job:
    runs-on: ubuntu-latest

    steps:
      - name: Build and Push the image
        uses: imsandeepreddy/Actions-Template@test2
        env:
          build_tool: ${{ steps.read-yaml.outputs.build-tool }}
