name: Use the Composite Action with Actions

on:
  workflow_dispatch:
  push:
    branches: ['test2']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read build-tool from YAML file
        id: read-yaml
        run: |
          build_tool=$(cat ./pipelineconfig.yml | yq e '.buildTool')
          echo "build_tool=$(echo $build_tool)" >> $GITHUB_OUTPUT
          #echo "{build_tool}=${echo $build_tool}" >> $GITHUB_OUTPUT
          echo $build_tool
        shell: bash
        env:
          path: ${{ github.workspace }}
      - name: test
        run: echo ${{ steps.read-yaml.outputs.build_tool }}
      - name: Build and Push the image
        uses: imsandeepreddy/Actions-Template@test2
        with:
          build_tool: ${{ steps.read-yaml.outputs.build_tool }}
