name: CI

on:
  workflow_dispatch:
  push:
    branches: ['test2']

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: imsandeepreddy/Actions-Template@test2
