name: Use the Composite Action with Actions

on:
  workflow_dispatch:
  push:
    branches: ['test']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Do anything elsee
        run: echo Pretend to do other things 

      # Uses the Composite Action
      - name: Build and Push the image
        uses: imsandeepreddy/Actions-Template@main
