name: Use the Composite Action with Actions

on:
  workflow_dispatch:
  push:
    branches: ['test2']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read build-tool from YAML file
        id: read-yaml
        run: |
          # Read the build-tool value from your YAML file
          build_tool=$(cat ./pipelineconfig.yml | yq e '.build_tool')
          #echo "::set-output name=build_tool::$build_tool"
          echo "{build_tool}=${build_tool}" >> $GITHUB_OUTPUT
        shell: bash
        env:
          path: ${{ github.workspace }}

      # Uses the Composite Action
      - name: Build and Push the image
        uses: imsandeepreddy/Actions-Template@test2
        with:
          build-tool: ${{ steps.read-yaml.outputs.build_tool }}
