name: Use the Composite Action with Actions

on:
  workflow_dispatch:
  push:
    branches: ['test2']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read build-tool from YAML file
        id: read-yaml
        run: |
          # Read the build-tool value from your YAML file
          build-tool=$(cat ./pipelineconfig.yml | yq e '.buildTool')
          #echo "::set-output name=build-tool::$build-tool"
          echo "{build-tool}=${build-tool}" >> $GITHUB_ENV
          echo $build-tool
        shell: bash
        env:
          path: ${{ github.workspace }}

      # Uses the Composite Action
      - name: Build and Push the image
        uses: imsandeepreddy/Actions-Template@test2
        env:
          build-tool: ${{ steps.read-yaml.outputs.build-tool }}
