name: CI

on:
  workflow_dispatch:
  push:
    branches: ['test3']

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: imsandeepreddy/Actions-Template/.github/workflows/main.yml@test3
